const planets = [
  {
    name: "Mercury",
    diameter: "4,880 km",
    mass: "3.30 x 10^23 kg",
    distanceFromSun: "57.9 million km",
    orbitalPeriod: "88 days",
    moons: 0,
    image: "./images/mercury.svg",
  },
  {
    name: "Venus",
    diameter: "12,104 km",
    mass: "4.87 x 10^24 kg",
    distanceFromSun: "108.2 million km",
    orbitalPeriod: "225 days",
    moons: 0,
    image: "./images/venus.svg",
  },
  {
    name: "Earth",
    diameter: "12,742 km",
    mass: "5.97 x 10^24 kg",
    distanceFromSun: "149.6 million km",
    orbitalPeriod: "365.25 days",
    moons: 1,
    image: "./images/earth.svg",
  },
  {
    name: "Mars",
    diameter: "6,779 km",
    mass: "6.42 x 10^23 kg",
    distanceFromSun: "227.9 million km",
    orbitalPeriod: "687 days",
    moons: 2,
    image: "./images/mars.svg",
  },
  {
    name: "Jupiter",
    diameter: "139,820 km",
    mass: "1.90 x 10^27 kg",
    distanceFromSun: "778.5 million km",
    orbitalPeriod: "12 years",
    moons: 79,
    image: "./images/jupiter.svg",
  },
  {
    name: "Saturn",
    diameter: "116,460 km",
    mass: "5.68 x 10^26 kg",
    distanceFromSun: "1.43 billion km",
    orbitalPeriod: "29.5 years",
    moons: 82,
    image: "./images/saturn.svg",
  },
  {
    name: "Uranus",
    diameter: "50,724 km",
    mass: "8.68 x 10^25 kg",
    distanceFromSun: "2.87 billion km",
    orbitalPeriod: "84 years",
    moons: 27,
    image: "./images/uranus.svg",
  },
  {
    name: "Neptune",
    diameter: "49,244 km",
    mass: "1.02 x 10^26 kg",
    distanceFromSun: "4.50 billion km",
    orbitalPeriod: "165 years",
    moons: 14,
    image: "./images/neptune.svg",
  },
];

export default planets;
